name: Publish blog postings

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - dev
      - build-test
      - publish-trigger

jobs:
  build_postings_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev

    - name: Build index.html
      run: curl ${{ secrets.BLOG_GOOGLE_DOCS_URI }} > index.html

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - working-directory: builder
      run: npm ci

    - name: Build postings
      working-directory: builder
      run: node app.js
      env:
        BLOG_CONTENTS_URI: ${{ secrets.BLOG_GOOGLE_DOCS_URI }}
        HTML_TEMPLATE_PATH: data/html_template.html
        DIST_URI: ../hugo/content/blog
        USE_HUGO: 1

    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build homepage
      working-directory: hugo
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./hugo/public
        publish_branch: master
