name: Publish blog postings

on:
  release:
    types: [published]

jobs:
  build_postings_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build index.html
      run: curl ${{ secrets.BLOG_GOOGLE_DOCS_URI }} > index.html

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: npm ci
      working-directory: builder

    - name: Build postings
      run: node app.js
      working-directory: builder
      env:
        BLOG_CONTENTS_URI: ${{ secrets.BLOG_GOOGLE_DOCS_URI }}
        HTML_TEMPLATE_PATH: data/html_template.html
        DIST_URI: ../postings

    - uses: stefanzweifel/git-auto-commit-action@v4.1.5
      with:
        commit_message: Publish postings automatically via Github Action
        branch: master
        file_pattern: index.html postings/**/*.html

